### ISSUE TITLE
Jason Brooke songs from Modland not working

### ISSUE THREAD

**Issue by sasq64** [sasq64/chipmachine#30]
uade only accepts .jcb extensions, but modland calls them .jb - needs renaming after download.

**Comment by mldoering** [comment]
Am Mon, 23 Nov 2015 01:06:41 -0800
schrieb Jonas Minnberg <notifications@github.com>:

> uade only accepts .jcb extensions, but modland calls them .jb - needs
> renaming after download.
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sasq64/chipmachine/issues/30

instead of renaming the files you can add the new extension to following
entry in eagleplayer.conf:
...
JasonBrooke		prefixes=jcb,jcbo,jb
...


I wonder why they use jb. I think both Wanted Team and Exotica use
jcb. -->http://www.exotica.org.uk/wiki/Jason_Brooke_(format)

**Comment by sasq64** [comment]
Strangely this does not seem to work...

**Comment by mldoering** [comment]
Am Tue, 24 Nov 2015 01:04:35 -0800
schrieb Jonas Minnberg <notifications@github.com>:

> Strangely this does not seem to work...
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sasq64/chipmachine/issues/30#issuecomment-159201374

Hmmh, any url so I can check the files, maybe packed or bad rips.

**Comment by sasq64** [comment]
It's not the file. Just changing the extension makes it work. Adding the extension to eagleplayer.conf does nothing, it still crashes unless the file is actually called jcb.

**Comment by sasq64** [comment]
Did a work around
